#+BEGIN_HTML
---
layout: post
title: How to Get More From Life
tags: [reading]
---
#+END_HTML

** 说明：
   来自于Scott Young的博客的一个PDF文件。Scott Young 就是那个一年学了一堆MIT在线课程的人。地址http://www.scotthyoung.com/blog/ 。

** 内容摘要
*** C1 Life is a work in Progress
    没什么实质内容，讨论下价值观人生观，全世界各有各的不同。
*** C2 Habits
    习惯当然很重要了，特别是好习惯的作用。所以要保持不断的修正自己的习惯。

**** how to
     1. 定义清楚习惯
     2. 严格执行30天
     3. 没把握就再执行90天
接着就是几个链接，没看了。发现链接会越点越多。
列个清单，然后就每月一个一个的清场吧。	
*** C3 Learning
**** School != Learning
     这个是当然了，特别是从兲朝一路走来的。
**** 作者的观点是T型人才，该实用性学习的就实用性，不用成为每个方面的master。
     换自己的话，还是“书宜杂读，业宜精钻”。旁边是一个有关T型人才学习的链接。这个算了吧，用了model这个词的....从本能上就知道，对个人基本没什么意义。
**** 学习方法上面
     还是注意联系旧知识。抽象的东西要形象化。注意知识点之间的联系，可以画图表示。
     当然还是老生长谈，他在译言上被翻译的一篇文章就是有关如何学习MIT的课程的。可以点那里看下，基本原则就是要注意整体的联系，不要迷失在细节上；多思考，用自己的语言表达，举一反三。

     其实自己也有方法论，基本也是这个原则，再加一条，“最好的学习方法就是教会别人。”还有要有笔记，别看现在自己学得欢，当心最后毛都没有，忘光光。能练习的，要有练习，光看书那是爽，什么都懂，回头看完了，再一问，白痴一样的，典型的没练习巩固的。某些东西，应试的方法是最好的。要是全面否定应试教育中的方法，那一定是naive，当然应试教育要全面否定。
**** Speed Reading
     用手指，别默读，多练习，注意一点“要有goal”。读书也要注意不要光读functionality的，天知道某些长远意义的知识会在哪里用到。

自己的经验是，有些书真的是看看封面就可以的，有些看看标题就可以了，特别是很多书喜欢来个案例分析分析的，只要不是准备深入了解的，都可以扫一眼跳过了。但是专业书一类的，不是快餐书的，想快读也读不快的，当然自己熟悉的领域的复习性质的，可以扫扫就OK。

*** C4 Productivity
    还是要有Goals，每天的、每周的，都要有。

    然后要有Calendar，这个东西太多了，Google的、icloud的、emacs的，重要的还是集中用好一个。GTD的东西太多了。

    同时还要注意log，基本就是类似《奇特的一生》了，org-mode就有这个功能。
    
    自己也要加一条，注意反馈。计划、行动、反馈、修正，这个得是个闭环啊。

*** C5 Social Success
    提了两条，作者自己也知道很空洞，说着简单，做起来难：
    1. Empathizing
    2. Communicating yourself.

    然后是注意平衡问题。这对内向的人没意义，从来都是社交太少。

个人的观点，为社交而社交纯属dt。还是从内而外的发自自然，读读心理书，当然，颜色心理学一类的就算了，针对个人的心理学估摸着都可以直接算作伪科学了，再读读哲学书，没事想想三个问题。有了自我才有社交的意义，否则社交干嘛啊，当然business is business，那真也算不上社交，那玩意叫做搞关系。

*** C6 Fitness
    保持健身，作者是素食主义，在这点上，没有肉真的对我是生不如死。不过自己也没有什么暴饮暴食的，注意控制和平衡饮食，其实素不素食倒不是关键。
    
    注意定下目标，有氧的、力量的。作者建议是：30天的习惯化；多尝试,找到自己喜欢的，什么合适就算了，所谓的“合适”其实就是自己喜欢的，不喜欢的还坚持，自虐的名额还是留在其他方面上，这里重要的不是类型，是坚持；找个伴，这不光健身什么的有用，其他方面也有用。
*** C7 Entrepreneurship and Finding Your Passion
    这基本就是Follow your heart。每个人每个人的不同。Life’s Too Short to Do Shit You Hate。
    
    作者又弄了一个概念Know Your Poverty Threshold，意义就是，怎样平衡生活水平和自己爱做的事情。做自己喜欢的事情，穷点也没关系，饿不死就可以。
    
    注意激情没有那么夸张，很平常的东西被人捧得太高了。
    
    还有业余的创业，这个不如看《Rework》。个人感觉创业也别捧得太高，就是自己觉得这里有的赚，来玩玩，或者自己觉得这里好玩，于是来赚赚，改变人类进步固然是好事，不过一群创业者们哪有都改变人类的，某些说不定就直接是盯着钱看的，那种就更不用顶个大帽子了，神圣化创业实在没好处，挖坑让人跳，始作俑者啊。

然后作者就是提出要多实践，从小做起，脚踏实地。也是老道理，没事就仰望仰望星空，然后该干吗就去干吗吧。知行合一，知行合一啊。

*** C8 Motivation, Confidence and Happiness
    Motivation就直接摘原文吧，简而言之就是找到一个自己喜欢的，然后坚持坚持再坚持。

#+BEGIN_HTML
It’s actually ridiculously easy. If you want to motivate yourself, spend 30-60 minutes brainstorming what you want from life and the action steps you need to take immediately to get there. If you aren’t motivated after a half-hour, you’ve done it wrong.
Patience, persistence and sweating out the work in soul-crushing moments of doubt and fatigue are the difficult part. I don’t admire the person who got started. I admire the person who showed up, every day, for years, without fail.
#+END_HTML

自信来源于经验，其实吧，自信基本都是盲目的，天知道经验能不能现用，多少人死在自己的经验上，对于现实这样的一个复杂系统来说，实在没什么解法。当然，没做过，说不定反而能做成。不过我们考虑下先验概率的话，有经验的，当然要更不盲目的自信点。

有关 Happiness那就是，人生不如十有八九，这是当然，哪有天天都得意的，点正的少数派就算了吧。何况这种主观判断的东西，你觉得不如意，别人反而觉得如意。保持心情的稳定，inner peace，要淡定。当然，这也要和自我有关系，没有自我的人，你让他淡定最后也是蛋疼。


*** C9 The Meaning of Life
    这就不记了，看下别人的meaning of life，然后再看看自己的，作为自省的一个机会就可以了。要保持自省......
