#+BEGIN_EXPORT html
---
layout: post
title: 自控力笔记
tags: [笔记]
---
#+END_EXPORT

看日期是9.03到手的。到上上周为止看了几遍，虽然这本书其实不是一本需要读很多遍的书吧，基本也算是一快餐书。而且设计的不错，每章节后面都有一个表格总结一下内容，再看的时候看看后面的表格就可以了。

全书基本说的就是如何抵制诱惑。一般都会先介绍理论性的东西，然后配合一个“意志力实验”来通过实践解决问题。

** C1
   神经学原理就是低级脑和高级脑的矛盾,里面提到了一句“注意力分散更加容易向诱惑屈服”，于是需要一些方法来提高注意力的集中能力， *5分钟冥想* 就出来了

** C2
   第一章提到的低级脑往往没法受控制，所以得加强下信心，说明下，其实诱惑还是可以抵制的，但是要注意到自己能够调整自己的状态。如何调整？ 就是 *三思而后行* ，也就是保持生理和心理的稳定，不要被冲动一时冲昏头脑。然后提出了一个评价指标，心率异变率，心跳慢下来就可以保持平静，集中注意力。还要注意，认识到自己的冲动，发现自己要做的决定其实不过是自己的冲动而已。然后既然有了心率异变率，那么就可以使用方法来控制了，其实就是减慢心跳，比如锻炼、饮食，然后还有个临时的方法， *有意识控制呼吸频率* ，长期的还是得靠锻炼了，所有还有 *5分钟锻炼* ，强度低的短期效果更好点。然后就是 *睡觉* 还有 *打盹* 。还有就是自控力有限，需要补充，所以不能一直太自控，要保持 *放松* ，因为压力也使要耗费自控力的。

** C3
   意志力是类似肌肉的，会慢慢的耗完，所以每天都要把重要的事情先做了。然后就是发现摄入糖分可以回复自控力，是光吃糖也不科学，继续深入，因为缺糖代表快完蛋了，所以要进入冒险模式了，但是这个只能用在原始社会。要有 *饮食方案* 要合理膳食，但是我发现这个和前面的理论实在是矛盾，算了，靠自己考虑，于是应该提高自己对缺糖的耐受度，然后就是多 *在小事情上有意识的锻炼自控力* 。后面又提出自控力是否真的有极限，会类似身体上长跑的时候有二次呼吸，挺过去就会感觉更好了，当然这个想法没什么直接的证据和理论支持，这本书也说了，无限意志力不太可能，但是还是有可能存在自己认为的疲惫其实是错觉的可能性，所以 *疲惫的时候要靠想想“我想要”来挺过去* 。

** C4
   行善之后更容易丧失意志力，因为自己没法准确评估，到底行善了多少，但是却有了借口给自己一点奖励。所以要 *取消许可，牢记理由* ，自己完成了目标的一部分时候要清楚自己真正的目标，还要有意识的记住自己行善的理由而不是记住我行善了。还有乐观会让自己明日复明日，于是要回复到现实中，明白 *今天和明天没有区别* ，所以要做什么就不要指望到明天了， DO IT NOW。

** C5
   多巴胺会对上瘾起作用，但是也可以利用多巴胺来实现自己的目标， *将有多巴胺的事情和讨厌的事情一起做* 。而多巴胺支持刺激了神经，完成刺激后，还是那个样子，所以要 *测试奖励的承诺* ，明白那些上瘾的事情往往最后的结果并不是自己实际期望的。当然，没有欲望也使很痛苦的，因为欲望使人年轻么， *合理控制欲望* 。

** C6
   情绪低落也会让自控力下降，上一章说的是欲望会降低，这一章说的是压力也会降低，因为也会影响多巴胺，所以要 *有效的降低压力* ，而不是用无效的方法。恐惧也会带来压力，所以也要注意控制恐惧，明白自己真正害怕什么，是否值得害怕。还有就是破罐子破摔的问题，对自己太狠往往就是这个结果，错一次情绪立马就下去了，所以要学会 *原谅自己* ，还是要保证自己情绪的稳定。还有就是过于乐观造成的虚假希望，计划和现实是有差距的，所以计划去实现才重要，停留在纸面上，不断地计划会让自己产生错觉，要保持一个 *乐观的悲观主义* 。

** C7
   人往往不能抵制住当下的诱惑而造成最后放弃了未来的机会，换句话来说，就是自己对自己的不负责任。其实这个何止对个人来说是这样，对政府和国家也一样，污染环境等等的，也使为了当下的诱惑牺牲自己的未来。原因似乎是自己的原始脑更加青睐于即时的奖励，不过有个解法，看不见当前的诱惑的情况下会好很多，所以可以 *保持距离* ，另外就是 *10分钟法则* ，有诱惑的时候，强迫自己延时10分钟去考虑长远的利益。然后就是 *降低未来的折扣率* ，考虑下未来的长期利益，如果放弃了，值得么。还有就是 *预先承诺* ，基本属于破釜沉舟这一类的，堵死自己的路，让自己只有考虑长期利益，或者犯了错就会有损失。还有就是要明白自己的未来和现在的区别，要看到自己希望自己未来是什么样子，这个似乎和多考虑长期利益一样， *预见未来的自己* ，想象自己的未来，给未来的自己写信等等。为了防止矫枉过正，书上又提了下，别太过于看重未来了，享受当下也需要。- -！
   
** C8
   意志力也使会传染的，这个相信每个人都是会体会，身边什么样子的人，自己也会向那个方向靠近。当然传染源也只会是自己感觉比较亲密的人。 *增强自己的免疫系统* 要每天考虑下自己的目标和可能的诱惑，提前打个预防针。 *感染自控力* 就是找些意志力强的典范来当偶像，这样也会被传染。也提到了社会认同等等，这个不多记了乌合之众、影响力还有认知偏差一类的书也都说到这些内容了。在我看来就是无解，你永远没有办法得到真正的自我的观点。不过如果社会认同向好的方向，自然对自己有利。 还有就是 *自豪的力量* ，看来就是被别人认同或者是自己成功挑战自我后的自豪感。 还有就是 *变成集体项目* ，因为一个人更难坚持下来。

** C9
   就像是越想睡觉越失眠的感觉，盗梦空间里面如出一辙。解决方法当然没法反抗了，因为越反抗越徒劳。所以就要 *忠实自己的想法，但是不能相信它* 。然后同理，对与欲望也使这样 *面对欲望，但是不要行动* ，承认欲望的不可控制，但是要注意自己之前的目标和承诺。后面的方法也使一个性质，既然越想越难忘，干脆就不要说什么 -我不要- ，改成我想要干什么就可以了。下一步则是更加危险的 *驾驭冲动* ，了解冲动的感觉，控制它，当然，这玩意很容易就变成没法控制了。

** C10
   引用原文吧：

   “如果说真的有自控力秘诀，那么从科学的角度来说确实有一个，那就是集中注意力”。
