#+BEGIN_HTML
---
layout: post
title: 2016
---
#+END_HTML

按照往常惯例, 又到了回顾与展望的时间...

简而言之, 二十几本书，七十多部电影，几本摄影图集，几个模型，一段感情，一次远行，还有浪费在刷知乎上的大把时间。

* 书
  主要内容是科幻小说和摄影教程. 这些里面, 看看了评分, 值得提出来的就是以下几本.
  1. 1453-君士坦丁堡的陷落: 我当时看完连带这心情沉重了好几天.
  2. 永恒的终结: 是本好书, 我打的可是五星.
  3. Designing BSD Rootkits: 电子书优惠里面买一堆, 就这本有点意思. 讲的怎么写内核插件, 怎么隐藏痕迹. 可以看出来, 内容上是很入门的内容, 何况现在的工作内容和这本书的内容完全没有关系, 但是, 开阔视野还是蛮有乐趣的.
  4. 理解曝光: 这书算是看过的这些教材里面最简单直接有效的了.
  5. 基地三部曲: 经典科幻, 心理史学. 虽然后面还有前传续集一类的, 然而精力有限. 看完三部曲就看不动了.
  6. 西方艺术新论: 牛津通识读本系列中的, 虽然是入门科普书, 考虑到这方面我连门都没入的, 还是给了我很多思考. 正好在学习拍照片, 也给自己了一些启发. 另外还看了一本量子理论, 但是我给的评价算是低, 不是很好.
  7. 巨人的陨落: 宏大的故事背景, 多条故事线的交织, 更重要的是, 翻译的让人读着很舒服. 确实是十分吸引人的一部小说.
  8. The Millionaire Next Door, 虽然是老书, 不过还是有点启发的.

* 电影
  十二月份确实连出好看的电影...几年看起来不错的电影/电视剧清单:
  1. 无人生还, 电视剧.
  2. 大空头.
  3. 星球大战7, 本身不算很好, 不过也不差. 浪费我几十块钱油费专门跑去看的imax版本.
  4. 人鬼情未了, 竟然是我情人节的时候一个人在家看的, 自虐不是一般般的.
  5. 大鱼
  6. 死侍, 这种贱贱风格的电影自然来者不拒.
  7. 惊情四百年
  8. 商海通牒, 和大空头基本凑一起看的, 顺便还有too big to fail.
  9. 浪潮
  10. 玛丽和马克思
  11. 王牌贱谍：格林斯比 & 独裁者
  12. 卡萨布兰卡
  13. 虎！虎！虎！
  14. 死亡诗社
  15. 芳芳, 可惜bilibili上是删减版.
  16. 血战钢锯岭
  17. 你的名字。

* 模型
完成了几个新的网络结构的改进, 训练与应用. 
1. 目前有能力在1024x576的视频中利用GPU实时检测, 最小目标大小可以到14x14像素, 当然, 这时会不稳定, 目前的后处理上来看, 应该会在20左右开始稳定.
2. 另有一个网络可以在CPU上完成15fps以上的检测. 当然, 局限性也很大. 增加容量降低性能后, 极限上可以检测6x6像素的目标, 但是只能GPU实时跑低清图上, 高清图上测试结果显示误识别有不少.

应用上, 网络2已经已经提供给其他部门使用. 另外, 为公司一个大客户提供的数据也应用的网络2, 目测未来换成网络1会性能更好, 更准确. 当然, 对外提供应用是其他同事负责的, 这些都需要很多额外的处理, 毕竟是到产品级, 不是demo. 之前的嵌入式ADAS也是在产品级优化和改进, 不过我已经基本脱离那条线, 除了自己的老代码非常少情况下我会帮着看下外.

Demo情况如下:
#+BEGIN_HTML
<iframe height=498 width=510 src='http://player.youku.com/embed/XMTkxMjQzNDA3Mg==' frameborder=0 'allowfullscreen'></iframe>
#+END_HTML
另有多个场景下的结果:
http://v.youku.com/v_show/id_XMTg4MDgyODUxNg==.html?spm=a2hzp.8253876.0.0.F3SGn7&f=29011331&from=y1.7-3#paction

其中, 05夜间, 03的是封闭测试, 其他都是开放测试. 夜间的能力只是凑巧不小心训练集中混入了一小部分夜间数据, 算是副产品.


回顾来看, 工作上依然不能让自己满意. 进度很慢, 软硬件资源不足, 自己的动力不足. 甚至人力也不足, 使用网络的目标检测的研发工作事实上只有我一人, 另有一个老同事可以偶尔帮把手, 也只是训练模型用于车道那块的检测. 当然, 比起之前已经好不少了. 之前还得管着另外一个嵌入式平台上的ADAS产品线, 尤其是之前还出现被大Boss强行抽调到其他项目上的恶心事. 手上的实习生也都留不住, 还没能帮上忙就已经走了. 

当然, 总结还是要关注自身, 自我批评开始: 

自己这一年也缺少系统性的学习与进步, 调参调的都要提前出中年危机了. 工作动力非常不足, 有点破罐子破摔的趋势了, 工作待遇其实算过得去, 然而缺少做事的动力了, 自我分析是前两年被恶心到了, 不知道换个环境是不是能改变. 工作进度慢, 其实也还是动力不足的问题. 所以, 工作上, 归根结底就一个原因, 目前我的工作动力不足.


* 其他
  其他就更加私人的内容了, 不多说. 只是我16年知乎上竟然刷了八百多万字, 这太不能忍了. 新的一年, 我计划降低到16年的一半以下, 然后多回答点问题一类的. 阅读量多分配点到其他方面上.
