#+BEGIN_HTML
---
layout: post
title: 我对创新的理解
---
#+END_HTML

前同事的一篇读书笔记
http://lpan1010.com/2016/07/27/%e5%88%9b%e6%96%b0%e8%80%85%e7%9a%84%e7%aa%98%e5%a2%83/

于是我决定也写一些自己对创新的理解. 当然, 这个决定做的很早, 只是现在终于开始实施了...果然是动力不足.

以上是今年一月份的开篇，然后，直到现在，我又开始继续了。

** 我所理解的创新的来源-多样性
    我个人认为创新本身就是可遇而不可求的，是一个概率事件，可以认为类似量子力学[fn:1]，在整个创新的过程中你是不可能知道结果到底会不会有创新的。
    
    那么怎样才能提高创新出现的频率呢？增加试验次数[fn:2]。我们可以通过大量案例的研究，统计出一个创新的趋势，和可能的影响因素，然后才可以更好的确认如何才能更加的创新。

*** 那么，能否挖掘创新的影响因素来直接促进创新？
    我个人对这个存疑，因为，创新本身的影响因素是难以琢磨的，不同的时期、不同的社会环境、不同的文化、不同的自然条件、不同的科技水平，促进创新的直接因素都有改变。譬如，我个人对基督教对欧洲影响的理解：
    基督教需要建教堂->需要高耸的教堂来更加接近上帝->我们要堆更加高的房子->石头是最好的材料，反正不缺（罗马早就已经发明混凝土，堆石头没问题）->我们需要立体设计图->我们开始关注3D，关注透视图，关注精确性->文艺复兴的画作开始有了透视->整个文化开始强调精确性->研究人体比例构造->理性主义的崛起->现代科学的诞生
    这样看着，简直是让人感叹，欧洲能够领导世界，这是个如此巧合的必然。当然，上面都是我的民科理论。回头看看中国，因为不爱用石头建筑，所以没有高楼的选择，在三维的精度上就不再有高标准的需求，只需要停留在可以搞定一定的高度的建筑这个水平上就可以，不存在对精确性的追求，所以难以找到理性主义爆发的突破口。

    那么，所以为了科学精神，我们现在要支持基督教么？显然，这样的逻辑会是个笑话。时期不同，自然条件不同创新的促进因素都不一样。我们可以利用历史统计的规律总结出很多因素，但是这些最多都是假设，直接因素不能随便的应用。

*** 如何促进创新？
    对于一个概率事件，我们怎么处理？唯一的办法就是增加可能性+多次实验，所以最后的结果就是：试错。
    所以，我对创新的理解就是，创新如同生物的进化一般，只能通过不断的试错才能够提高产量。那么，人类对待生物进化的努力是什么？保护生物多样性。
    所以，要想试错，必须保护多样性。这也已经成为我自己的一个信条：一个社会必须保护其多样性才能够保证其活力，保证文化、科技的繁荣。
** 创造创新的环境
*** 保护多样性
    按照我的民科观点，我们无法提供促进创新的直接因素。唯一能做的就是提供创新的土壤，一个多样性的环境，让各种可能的路线都能够在这个环境中尝试，最终出现新的曙光。
    + 于个人，我们不能顽固的坚守一个想法，需要保持开放的心态。
    + 于家庭，要减少封建家长作风，不玩一言堂，尊重家庭成员。
    + 于企业，要增加交流、放手给员工、保持企业多样化/开放的价值观。
    + 于国家，不能万马齐瘖，必须百家争鸣。
*** 必须提供自底向上的创新途径
    自顶往下的路径只有两个可能：
    1. 一个明确的目标、项目，造成的结果就是，难以保证多样性，而且因为目标明确，必须技术成熟甚至保守。创毛新？[fn:3]
    2. 一个含糊的目标，造成的结果就是，务虚、务虚、务虚。一个含糊的目标犹如一个含糊的屁，放完了就没了。

       
    创新的来源就是自底向上，多样性是由数量来保证的，任何一个管理体系，肯定上层的数量少，没有数量，就难以保证多样性。更重要的是，上层由于管理层级，已经脱离了各种创新路径尝试的具体工作，失去了指导能力。在我看来，"创新"能够自顶向下的，只有一个可能，高层看到外部的一些公司的创新成果和新的路线，由此开始推进自己公司的“创新”，明显的，这个是打引号的，这只能是跟随和追赶，其实就是自顶往下的第一种情况。

*** 压力与创新
    高压力下是否影响创新？我的猜测是：没有直接的关系。但是人类有一个通病，一旦在有压力的情况下会处于应激状态，注意力是高度集中的，这个时候是没法谈多样性的。譬如，你大草原上被狮子盯上了，这时候除了紧紧盯着狮子的动向根本就不可能再分精力到其他事情上。

    所以，我的民科观点是，压力只要没有影响到多样性，就不会对创新有负面影响。

    那么，反过来说，是否有促进作用？ 毕竟，生物的进化不也是有生存压力的么? 在我看来，进化过程中个体并没有感受到生存压力，自然只是做了一个选择。换句话，是你先走了这个创新路径，然后自然才决定你是否能够活下去。所以，我不认为压力能够对创新产生直接的促进作用。但是，压力会促使你中断当前的创新路径，去尝试其他新的创新路径，间接的增加了新尝试的次数。

*** 艺术对技术创新的促进作用
*** 文化艺术的意义重于技术
*** 对人的关怀与尊重
    科技以人为本。
*** 多样性的相对性

** 应用与扩展
    支持多样性
* Footnotes

[fn:1] 作为民科的我，我要提出一个新的理论，量子创新学，呵呵。

[fn:2] 我tm太机智了，呵呵。

[fn:3] 当然，我看这个方式很适合技术追赶，比如神舟飞船、高铁。





