#+BEGIN_HTML
---
layout: post
title: 2012的电影和书盘点
tags: [nothing]
---
#+END_HTML

年纪不小了，总结也要开始严肃起来了。要细致、要严谨、要成为共产主义战士。

算算自己今年的书和电影吧,从自己的豆瓣上的记录拿来的。

** 书
*** /鲁滨逊漂流记/ 完成
    从小就想看，一直都没看的。
*** /史蒂夫·乔布斯传/ 完成
    我不是果粉，但是乔布斯真是成就惊人。
*** /胡适口述自传/ 50%
    自己看着感兴趣的章节。
*** /Linux/Unix设计思想/ 快速通览
    和 /Unix编程艺术/ 基本一样，看过的就没必要看这本了。
*** /通往奴役之路/ 复习
    部分章节
*** /谁会认错/ 完成
    什么时候我能完全做到知错、认错、改错？
*** /乌合之众/ 收尾
    扔那好长时间还差一章节，就收尾了。
*** /链接器和加载器/ 复习
    感觉还要再看一遍 /程序员的自我修养/
*** /集体智慧编程/ 25%
    网上似乎都没得卖了。
*** /编码/ 90%
    还剩一章收尾。从初中物理的电路构造出计算机。数字电路、汇编、计算机组成等等。
*** /重构/ 快速通览
    零零散散的最佳实践，还是要靠从实践中领悟和学习。
*** /自控力/ 完成
    意志力十分重要。
*** /上帝掷骰子吗/ 完成
    物理史话，科普读物。
*** /论中国/ 90%
    由于国庆假期在家看的，时间有限，还剩几十页没看。
*** /动物庄园/ 完成
    自从看完 /1984/ 之后就天天想看看这本小说了。
*** /论人类不平等的起源/ 完成
    如果不是翻译的问题，那就一定是我智商的问题。浑浑噩噩看完的。
*** /失败的逻辑/ 完成
    复杂系统、控制、混沌等等。
*** /影响力/ 75%？
    忘了自己看到哪里了，断断续续看的。
*** /浪潮之巅/ 完成
    技术不是万能，没有技术万万不能。
*** /数学之美/ 完成
    入门的科普读物。
*** /信息检索导论/ 完成
    IR的入门，教科书。
*** /金融的逻辑/ 完成
    电子版的，有意思的书。
*** /谣言粉碎机/ 完成
    快速通览的。
*** /华尔街的扑克牌/ 完成
    同 /论人类不平等的起源/ ....两者都在火车看的...果然。
*** /旅行，人生最有价值的投资/ 完成
    睡前读物。磨磨唧唧看了一段时间才完成。
*** /实用Common Lisp编程/ 50%？
    看了SICP的一部分又重新看了这本，感觉要正常多了。
*** /计算机程序的构造和解释/ 30%?
    对于习惯指令式语言的人类来说...异次元世界的东西真的很brainfuck。
*** 还有2-3本书名不方便列出的电子版书
    当然，都是符合社会主义价值观的。

** 电影
*** /蝙蝠侠：黑暗骑士崛起/
    高富帅做好事不留名，雷锋精神永流传。
*** /只有你/
    女主好漂亮，故事好多泪。可惜我不多泪。
*** /初恋这件小事/
    女ds逆袭。女ds逆袭故事的大家都喜欢，男ds逆袭的就....谁说这个世界已经男女平等了？我要求真正的消除性别歧视。
*** /壮志凌云/
    终于看了，多少年魂牵梦绕。
*** /V字仇杀队/
    拜CCAV6所赐，瞬间网上遍地都是，总菊等着自爆吧。
*** /人再jiong途之泰jiong/ 影院
    搞笑，真的搞笑。同时，也就搞笑了。
*** /巴顿将军/
    从小时候开始电影刚开始的星条旗下的演讲那幕就深入我心。全篇的镜头运用都是王。
*** /少年派的奇幻漂流/ 影院
    剧情、配乐、特效、画面没有落下的。
*** /诱惑法则/
    混乱的青春...我怎么就没赶上那个好时代。哦，忘了，我选了hard模式。
*** /危情三日/
    真男人，真汉子。爱人不疑，疑人不爱。纽扣恒久远，一颗永流传。
*** /谍影重重/ 1-4
    为了看4，该复习的复习，该补课的补课。
*** /里约大冒险/
    忘了是不是今年的了。
*** /搏击俱乐部/
    同上。
*** /Ice Age 4/
    保留曲目。
*** /美丽人生/
    好爸爸，就要让孩子生活在童话中。
*** /亚伯拉罕·林肯：吸血鬼猎人/
    动作片。
*** /环形使者/
    看完竟然没印象了。快餐片么？
*** /野蛮人/
    考虑到以前的 /gossip girl/ ，于是看了看。
*** /大武当之天地密码/
    NC片，我还忍着看完了。也忍住没打低分，当然，自从 /新生活大爆炸/ 占据了我的douban一分榜后，我就没法给别的片打低分了，从此我的评分体系也就崩溃了，毁了我的评分观。
*** /光晕4：航向黎明号/
    Halo自然一定要看。我爱士官长。
*** /坏中尉/
    平平淡淡的才见功力。
*** /太空一号/
    我爱男主和男主的台词，勉强加上女主的脸吧。
*** /潘神的迷宫/
    高深莫测，目前我还是不知深浅啊。
*** /胡桃夹子：魔境冒险/
    艾丽·范宁好可爱。男主的名字，对中国人来说天生就有违和感啊！！！当然，里面还是有很多讽刺和隐喻的，这是英国佬的习惯么？
*** /一天/
    最后最后的那天的回忆真的是点睛之笔，让人飙泪的泪点，从此与众不同。我飚了？没飚？
*** /黑镜/
    恩，就是那个black mirror....
*** /神探夏洛克/
    是今年出的最新一季的么？
*** /罗宾汉/
    从小罗宾汉就是偶像之一，尽管只是耳闻其名。我为什么这么喜欢个人英雄主义呢？
*** /敢死队2/
    纯粹为了看mans，错了，应该是men。
*** /飞屋环游记/
    一老一小走天涯，但其实那对两小无猜才是戏份中的高密度物质。相守就是历险，窗内也有世界。
*** /泰迪熊/
    毁三观，从此看泰迪熊的广告就....是德芙的广告么？真的好想要一只，但是，这其实就是基友的写照啊。没有毁三观的基友的人生，算不上完整的人生。
*** /猫鼠游戏/
    隐约记得以前看过。传奇一般。
*** /国王的演讲/
    英国人都是演技派，实力派，底蕴派，莎翁派。
*** /致命ID Identity/
    正常人看的结果都是“我想多了”。
*** /本杰明·巴顿奇事/
    不公平，越活越年轻。
*** /怦然心动/
    女主好漂亮，我说的是她小时候。。。
*** /普罗米修斯/
    不是我喜欢的科幻片，何况自己之前没补课。
*** /飓风营救2/ 影院
    因为1，所以2.。。可惜2没1好看。
*** /野战排/
    肯定是经典，所以...
*** /寂静岭/
    不爱玩RPG的人，所以看这个天生有劣势。
*** /汉密尔顿：国家利益/
    徒手格斗等等， /Taken/ 的翻版啊。
*** /光荣/
    光荣就是glory。
*** /狗镇/
    我竟然坚持看完了。以后有信心看舞台剧了。
*** /完美风暴/
    男人都爱乔治·克鲁尼
*** /总统杀局/
    还没收尾，同上。
*** /伊娃 Eva/
    女主和小女主都好看......男主是个幸福的男人。EVA这名字...为什么有违和感呢？
*** /秒速五厘米/
    新海诚，新海诚，新海诚。想复习 /云之彼端/
*** /超级战舰/ 影院
    打呀打呀打呀打...逻辑是不需要的。
*** /赛德克·巴莱/
    短版，够用了。
*** /黑衣人3/ 影院
    保留曲目。
*** /超能失控/
    苜蓿地后就免疫了...
*** /晚秋/
    普通片吧，有段时间了，忘了。
*** /泰坦尼克号 3D版/ 影院
    ......
*** /碟中谍4/
    保留节目。
*** /战马/
    不习惯以马为主角所以感觉没主角么?
*** /白兔糖/
    一小部分，记得回头看完。
*** /龙门飞甲/
    算了，就这样算了吧。
*** /那些年，我们一起追的女孩/
    电影配乐从此成为保留曲目了。
*** /big bang s6/
    保留节目。
