#+BEGIN_HTML
---
layout: post
title: DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
tags: [nothing, thoughts]
---
#+END_HTML
#+TITLE: DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#+AUTHOR: 秦暕
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \setCJKmainfont{Microsoft YaHei}
* 说明
  无意中更新switch-window插件，在代码里发现这样的一个金矿，里面的版权声明如下：
#+begin_quote
Licence: WTFPL, grab your copy here: http://sam.zoy.org/wtfpl/
#+end_quote
  当然，以我的验货无数的火眼金睛，立马发现了该licence的反常，心中立马补了一句“wtf”，立马就点进去了。
* 内容
对于法律相关条文具有天生仇恨的程序员应该可以对这个安心，全文如下：
#+begin_quote
  DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
                    Version 2, December 2004 

 Copyright (C) 2004 Sam Hocevar <sam@hocevar.net> 

 Everyone is permitted to copy and distribute verbatim or modified 
 copies of this license document, and changing it is allowed as long 
 as the name is changed. 

            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION 

  0. You just DO WHAT THE FUCK YOU WANT TO.
#+end_quote
第一次看到这么赏心悦目的license。我的人生又少了一份遗憾，心中不免哼起来Lily Allen的那首“Fuck you”。当然，法律是严肃的，所以有FAQ的哦，地址还是在官方网站上。除了最后那几个yes，you can（这里我怎么又想起来了观海兄），还有这个亮点：
#+begin_quote
**** But profanity is offensive!
     You know what? Fuck your stance on profanity. Fuck your priorities in life. The WTFPL is about fucking freedom and we mean it. Freedom means freedom to copy and modify and share works of art and science with the rest of mankind, but also freedom to be gay and marry and have crazy gay sex, freedom to have tattoos, freedom to say there is no God, freedom to take the pill, freedom to have an abortion. People die for being gay or atheists. Don’t tell me that there is something sacred enough that it must be protected from the mere existence of the word “fuck”. If the F in WTFPL offends you, then fuck you and your beliefs. Triple fuck you.
#+end_quote
Yeah，triple fuck you.不免让我想起来黑客帝国里的Trinity，霸气都是由内而外的。
* 客户
  1. el-get竟然赫然在列，官方网站上的showcase里面给了项目在github上别人提的issue，当然已经close了，close的原因，还是请自己去看看吧 https://github.com/dimitri/el-get/issues/474 。我还是太naive啊，孤陋寡闻孤陋寡闻啊。
  2. 还有本篇文章，特别注明，使用WTFPL。

