#+BEGIN_HTML
---
layout: post
title: Why *unix ?
tags: [nothing, thoughts]
---
#+END_HTML
#+TITLE: Why *nix
#+AUTHOR: 秦暕
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \setCJKmainfont{Microsoft YaHei}


这个问题实在是，蛋疼，充满争议，打标签被动式之王复数形式之一，起码曾经是。不过最近云计算什么什么的玩意突然把这个问题给消除了，现在，没用过*nix，你都不好意思说出口。简历上怎么也得贴一个，熟悉*nix环境，以显示或者说标榜自己的Geek、程序员的一面。

不过（为什么我要用“不过”这个词呢？）按照我自己那点微不足道的经验来看，使用*nix的作用还是很大的，当然，这里仅仅是限制在程序员的范围内。
* 观点
** CLI是落后的、原始的、低级的
   这个麽，实在是没有什么好吐槽了，一点战斗力都没有的观点，只能说，有这样的观点的倒是真是落后的。find、grep、sed、awk、sort和管道，仅仅需要这几个东西就足以推翻猜想了。只要是尝试过shell脚本结合一些小工具
   的作用，这样的观点休矣。当然，CLI并不落后，不代表CLI就一定代表先进，CLI不落后，也不代表GUI就落后，这句多余的废话纯属，没错，废话。
** 用来装逼的么？
   这里其实想想费曼先生的那本书名“what do you care what other people think”，用CLI的逼格岂是你们这些泥巴种能够理解的。我们常常想不通有钱人为什么花泥马那么多钱买包包，或者买个小陆龟放生蔚蓝色的海洋，往往的结论就是“装逼”，其实么，人家只是have fun。别红眼，人家就是钱多多，哪天内心空虚寂寞冷了，就烧点钱暖暖。当然，把陆龟往大洋里放的，那真属于不是逼格不够就是智商不够的问题。同理，我开心整个终端噼里啪啦弄键盘，have fun。当然，如果你弄个终端只是为了让别人看见你在用终端，等没人看了就不用了，那么，这句话还真说对了。
** 有用么？
   这个么，起码简历上有光.....折腾这个东西，确实浪费时间，也别信什么折腾好了之后就一劳永逸的骗子，有心思折腾不停的，总有理由挑战新玩法，有事没事好奇心就要被挑逗起来，从此废寝忘食。不过这个过程倒是像是从黑盒测试到白盒测试的过程，开始，你什么都不清楚，找个人问下，给你个命令就照着敲，一个字母都不敢改，那简直就是巫师的魔咒，整个系统就是个黑盒子，渐渐的，你慢慢明白了命令的意义，明白了配置文件的位置与作用，整个系统稍微的明了，开始了定制化之路，自己没事改改玩，看见别人的东西不错，就拿来自己捣鼓捣鼓。然后...我觉得我没资格继续说下去了。To follow the path: look to the master, follow the master, walk with the master, see through the master, become the master. 真的有用么？我想其实没有用，但是这个过程却有用，解决问题的能力、理解问题的能力、自己进行主题阅读的能力、学会独立学习的能力、对系统的通过自己的实践得到的观点，这些副作用留下的软能力才有用。 
** 那些缺点呢？
   万物都有缺点，何况*nix基本都是意外的产生，有的貌似是两人为了打游戏写的，有的是为了写着玩，发了个邮件没想到成正果了。看来看去基本就一个缺点，网银，这个吧，货到付款吧，总要有个缺点让你委屈委屈的吧，否则不就完美了么。

* 作用
** 开窗
   不管承认与否，*nix环境下相对更加丰富多彩，譬如打开了一扇窗进入了新世界，花花绿绿的多开心。如果只用某一个东西，总会限制自己的视野，错过很多，当然，多了也容易分心，不过，井底之蛙的专心，与看遍世界后的专心境界大不同。
** 深入
   为什么能深入呢？因为你折腾了。最开始的亲自用编辑器写代码用编译器编译最后执行，就已经剥离了IDE的包装。之后对问题的理解的角度就不同的，折腾么，就是一个遇到问题然后解决问题，没有问题制造问题的过程，当然解决问题也有很多方法，但是用*nix环境的好处就是，总有些问题你非得自己亲自动手才能解决，也就是，逼着自己向白盒方向前进。没几次折腾，就慢慢开始深入了解问题了。
** 软实力
   就像有用么一样，其实本身的作用未必有多大，简单的熟悉下命令也可以很好的使用了，但是相对来说还是和编程调用API没有多大区别，命令么，不就是shell里面的API么，单纯就调调API挺没有出息的，起码得问问为什么API要这么设计，优缺点如何，然后再深入深入问问API怎么实现的。这时候就开始挑战智力水平了，因为往往这个时候就不再停留在知识的水平上了，而是进入了融会的水平，知识么，也就是多记多背就可以，交给计算机就可以，要么是Google，要么自己整一个：硬盘＋lucene，但是运用知识背后的能力就不是计算机能够处理的，人和计算机比，能找到的竞争壁垒，目前来看也就是这个了，比知道的多、记得多，都不屑于比，你能比Google知道的多、记得多？但是Google没法拿这些知道的、记得的解决问题，人才有这个能力。
* MAC OS
  好处就是真的折腾少了，不用有系统升级强迫症候群，软硬件结合的好，电池、散热、噪音都是过去，驱动不再是噩梦，实际情况是，“驱动是什么？”自己再整个homebrew或者mac port，从此生活好滋味。其他的，没感觉和Ubuntu等等有什么区别。除了有个什么Apple Script，可以脚本化GUI进程之间的通讯。
  但是，折腾少了也就没有了其他的*nix的那些好处了，没法再深入了解表层后面的东西了，所以理想的状态就是，首先用GNU/Linux，熟悉了再转Mac OS。直接用的结果是，看着花哨的界面哈哈傻笑，很多有用的或者说是有威力的东西放在那里自己却从来不知道为何物。
* 白眼狼
  用了东西当然要反咬一口，连白眼狼都没有做成真的会很亏本的啊。对一个东西，批评的难度一般都要大于夸奖。因为优点往往是被人明了的，而批评要能够批评个所以然出来就需要对这个东西有很好的理解，当然，那些瞎批评的就不算数了。所以没事看看XX痛恨者手册是颇有必要的，这样才能培养自己的白眼狼的潜质，同时么，回头引用个两句话，也可以提升自己的逼格啊。所以么，买东西也一样，盯着好评看一点意义都没有，你都打开商品页面了，说明准备要买了，那还看你妹的好评呢，赶紧看差评，那才是王道，知道了缺点再买，使用的时候才会客观冷静不狂热。再进一步，知道了缺点还能爱，那才是真爱。
* 保护逼格
  麻瓜们往往还是对于装逼表现的十分崇拜的，所以么，在麻瓜面前，逼格高低不是问题，因为，再低都比麻瓜高，麻瓜都不知道装逼为何物的。可惜的是泥巴种们，爱骂装逼问题，所以逼格要用心保护。
  1. 雷蒙德的黑客X部曲，入门逼格必备，哪怕没有照着做，背下来几句，在一年级的泥巴种面前已经具有良好的智力优越感了。人家的UNIX编程艺术也要看，KISS要时刻挂在嘴边。要表现出恨不得额头上打个Geek或者hack标签的激情。当然，最近貌似比较流行Paul，黑客与画家不管看没看完，书要多翻翻，不能全新，瞬间暴露，当然也不能翻烂了，逼格，拼的就是一个度。
  2. 怀旧与历史感是任何领域提升逼格的必备，比如音乐要弄Classic的，哲学要讨论讨论柏拉图、康德、黑格尔，哪怕讨论讨论向量空间也要扯出来希尔伯特，瞬间高大全形象飙升。专业史是很重要的，起码在吹牛X上可以占据主动，其他的好处么，冷暖自知。
  3. 最新发展。就像要fashion,巴黎时装周哪能少。硅谷最近怎么怎么了，那就像自己家后院一样清楚了。要谈就谈facebook的取代者会是谁，说什么中国的facebook会是谁立马暴露你土鳖一面，一看就知道和腊肉一个德行，也就懂个毛。风投的动向，要比被投资的公司还要明白清楚。当然，天天挂嘴边那不行，那是XX分析师，连个May I help you都是满口的伦敦乡下腔外带苏格兰味，还忘了那点睛的sir。当然，以上是非技术范围的，还得有技术范围内的，某某新推出的技术，当然，直接说出来那就是逼格跌停，要和历史联系起来。最新技术其实是XX年前的技术的翻版，然后说出个“所以然”来，这里的引号表示引号中的内容无所谓。新东西出来当然要立马试试，然后和别人聊天的时候表现下自己玩过的心态，谨记是玩玩，深入么，hu cares，哦，现在是she cares了。
  4. 形象气质佳。暧昧之心，人皆有之。是爱美，不小心暴露了地球人的本质。短裤加T，T还得是XX开源会议送的，要是有个Fuck MS，那简直就是大神级人物。Ubuntu的圆圈圈太俗，都烂大街了，再不济大便的小九九也行，gentoo，LFS、Apache等等对于提升逼格是有作用的。拖鞋和那忧郁的眼神、唏嘘的胡茬子、神乎其神的不离键盘的指法，还有那杯drymartine，恩...没有酒，有也是啤酒，看不起的就是那些喝洋酒装逼的人。
  5. 神秘主义与哲学。没错，Hello World你都要蒙上一层神秘主义的面纱，“你知道这最简单的程序背后计算机的运行过程么”。哲学，没错，哲学与装逼简直有天然的联系，而且要尽量的形而上。综合来看，就是要有讲故事的能力，让观众觉得：挖～～好NB。
  6. 没有好坏。评价什么什么的，大是大非的要绝对狂热，小是小非的要瞬间转换活用辩证法，批评就是装逼的一种形式。一般都要加个“但是”或者“不过吧”。
  7. 小众，绝对的小众。小众给人的错觉就是高端。人多的还就不玩，要有这样的心态，宁可做正态分布某一端的SB也不做中间的那堆不知道是什么东西的东西，俗，太俗。优越感，优越感，没错，就是那种由内而外的优越感，要找好感觉。


  本节内容村吐槽。以至于自己都要精神分裂了，不能继续了，不然疯了对不起父母了。



















































